
  export const print={
    category:"Category",
    data:[{
      id:1,
      "shoetype":"heels",
title:"Women Red heel sandle",
description:"trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size",
Cart:"Add to Cart",
Instock :true,
price:"89",
 icon:"star", 
 icon1:"star",
 icon2:"star",
 icon3:"star",
 icon4:"star",
 sizes:"S",
 sizem:"M",
sizel:"L",
 wishlist:"love",
 "image":require("../image1/images5.jpg"),
"image1":require("../image2/download.jpg"),
"image2":[require("../image1/images13.jpg"),
       require("../image1/images13.jpg"),
       require("../image1/images13.jpg"),]

},
  {id:2,
    "shoetype":"sneakers",
    description:"trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size",
Cart:"Add to Cart",
Instock :true,
price:"89",

sizes:"S",
sizem:"M",
sizel:"L",
title:"Women Red heel sandle",
icon:"star",
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
wishlist:"love",
"image":require("../image1/images12.jpg"),
"image1":require("../image2/download2.jpg"),
"image2":[require("../image1/images13.jpg"),
       require("../image1/images13.jpg"),
       require("../image1/images13.jpg"),]
},
  {id:3,
    "shoetype":"sandler",
    description:"trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size",
Cart:"Add to Cart",
Instock :true,

sizes:"S",
sizem:"M",
sizel:"L",
wishlist:"love",
price:"89",
title:"Women Red heel sandle",
 icon:"star",
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
"image":require("../image1/images1.jpg"),
"image1":require("../image2/download1.jpg"),
"image2":[require("../image1/images13.jpg"),
       require("../image1/images13.jpg"),
       require("../image1/images13.jpg"),]
 },
  {id:4,
    "shoetype":"boot",
    description:"trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size",
Cart:"Add to Cart",
Instock :true,

sizes:"S",
sizem:"M",
sizel:"L",
wishlist:"love",
price:"89",
icon:"star",
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
title:"Women Red heel sandle",
"image":require("../image1/images4.jpg"),
"image1":require("../image2/download2.jpg"),
"image2":[require("../image1/images13.jpg"),
       require("../image1/images13.jpg"),
       require("../image1/images13.jpg"),]
},
{id:5,
  "shoetype":"boot",
description:"trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size",
Cart:"Add to Cart",
Instock :true,
wishlist:"love",
price:"89",
icon:"star",

sizes:"S",
sizem:"M",
sizel:"L",
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
title:"Women Red heel sandle",

"image":require("../image1/images5.jpg"),
"image1":require("../image2/download.jpg"),
"image2":[require("../image1/images13.jpg"),
       require("../image1/images13.jpg"),
       require("../image1/images13.jpg"),]
},
{id:6,
  "shoetype":"boot",
  description:"trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size",
  Cart:"Add to Cart",
  Instock :true,
 wishlist:"love",
price:"89",
icon:"star",

sizes:"S",
sizem:"M",
sizel:"L",
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
title:"Women Red heel sandle",

 "image":require("../image1/images7.jpg"),
 "image1":require("../image2/download1.jpg"),
 "image2":[require("../image1/images13.jpg"),
 require("../image1/images13.jpg"),
 require("../image1/images13.jpg"),]
},
 {id:7,
    description:"trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size",
    Cart:"Add to Cart",
    Instock :true,
    "shoetype":"boot",
 wishlist:"love",
price:"89",

sizes:"S",
sizem:"M",
sizel:"L",
icon:"star",

icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
title:"Women Red heel sandle",

   "image":require("../image1/images8.jpg"),
   "image1":require("../image2/download2.jpg"),
   "image2":[require("../image1/images13.jpg"),
   require("../image1/images13.jpg"),
   require("../image1/images13.jpg"),]
},
    {id:8,
      "shoetype":"boot",
      description:"trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size",
      Cart:"Add to Cart",
      Instock :true,
      
 sizes:"S",
 sizem:"M",
sizel:"L",
 wishlist:"love",
      price:"89",
      icon:"star",
      
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
     title:"Women Red heel sandle",
     "image":require("../image1/images9.jpg"),
     "image1":require("../image2/download.jpg"),
     "image2":[require("../image1/images13.jpg"),
     require("../image1/images13.jpg"),
     require("../image1/images13.jpg"),]
},
      {id:9,
        
 sizes:"S",
 sizem:"M",
sizel:"L",
       description:"trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size",
         cart:"Add to Cart",
        Instock :true,
        "shoetype":"boot",
 wishlist:"love",
        price:"89",
        icon:"star",
        
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
       title:"Women Red heel sandle",
       
       "image":require("../image1/images10.jpg"),
       "image1":require("../image2/download1.jpg"),
       "image2":[require("../image1/images13.jpg"),
       require("../image1/images13.jpg"),
       require("../image1/images13.jpg"),]
},
        {id:10,
          "shoetype":"boot",
         description:"trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and sizetrending heels shoe, with great quality varies in color and size,trending heels shoe, with great quality varies in color and size",
          Cart:"Add to Cart",
          Instock : true,
          
 sizes:"S",
 sizem:"M",
sizel:"L",
          
 wishlist:"love",
          price:"89",
          icon:"star",
icon1:"star",
icon2:"star",
icon3:"star",
icon4:"star",
         title:"Women Red heel sandle",
         
         "image":require("../image1/images11.jpg"),
         "image1":require("../image2/download2.jpg"),
         "image2":[require("../image1/images13.jpg"),
         require("../image1/images13.jpg"),
         require("../image1/images13.jpg"),]
  }

], }
